### ISSUE TITLE
Information included in SimpleResult

### ISSUE THREAD

**Issue by qixinbo** [GreenDelta/olca-ipc.py#16]
Dear developer,
From the api of SimpleResult, it is found that it contains ImpactResults and FlowResults.
Does it also contain the process-related information? For example, the "Process flow contributions", "Process impact contributions" in the excel report?
Thanks in advance!

**Comment by angaik** [comment]
Hello @qixinbo,
You can get the information of Process flow & impact contributions in the excel report, when you set the CalculationType as "CONTRIBUTION_ANALYSIS" for the setup.

I attach a txt file as an example to explain more clearly.
[contribution_analysis_olca.txt](https://github.com/GreenDelta/olca-ipc.py/files/9438683/contribution_analysis_olca.txt)

**Comment by qixinbo** [comment]
Hello @angaik thanks a lot for your kind explanation!~
