### ISSUE TITLE
Questions about installing Olca to connect to Jupyter Hub. 

### ISSUE THREAD

**Issue by BastianKoenig** [GreenDelta/olca-ipc.py#17]
Hello, I have tried to connect from OpenLCA to Python. What exactly needs to be installed? I have proceeded exactly as in 'GreenDelta/olca-ipc.py´ described. But then I always get the following error message: 

![grafik](https://user-images.githubusercontent.com/46598527/145130044-4daade99-5937-4487-9caa-ae212d11c34f.png)

**Comment by Miguel-g-c** [comment]
Hi @BastianKoenig,

Try to install the latest development version: `pip install -U git+https://github.com/GreenDelta/olca-ipc.py.git/@master`

We have recently introduced some changes. Also, be sure that the Python version you are using is 3.7 or greater.

**Comment by BastianKoenig** [comment]
Thanik you! 
I did not install pyhton with the function from the path and this led to errors.

**Comment by sunderingtitan82** [comment]
Hi Miguel, when using PyCharm I do install the olca package but an I guess similar problem shows up:

`C:\Users\emper\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/emper/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:/Users/emper/PycharmProjects/pythonProject/main.py", line 1, in <module>
    import olca
  File "C:\Users\emper\PycharmProjects\pythonProject\venv\lib\site-packages\olca\__init__.py", line 4, in <module>
    from .ipc import *
  File "C:\Users\emper\PycharmProjects\pythonProject\venv\lib\site-packages\olca\ipc.py", line 5, in <module>
    import olca.schema as schema
  File "C:\Users\emper\PycharmProjects\pythonProject\venv\lib\site-packages\olca\schema.py", line 7
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

Process finished with exit code 1`

I should install olca as a package in my environment directly as previously mentioned right? The PyCharm package installer is not installing the lastest development version...

**Comment by Miguel-g-c** [comment]
Hi @sunderingtitan82, you can [install packages from a version control system in PyCharm.](https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html#install-from-vcs) Also, check that you are using Python +3.7.

**Comment by PortiaMasibi** [comment]
Hi @Miguel-g-c I am getting the same error from Jupyter Notebook but I followed all the steps above

**Comment by Miguel-g-c** [comment]
> SyntaxError: future feature annotations is not defined

Hi @PortiaMasibi what error are you getting? Please, post the error log here. Also make sure you are using the latest development version and Python 3.7 or greater.
