### ISSUE TITLE
upstream_tree_of failed

### ISSUE THREAD

**Issue by 20cents** [GreenDelta/olca-ipc.py#25]
Hello,

I try to use the `function upstream_tree_of` followind this exemple: (Of course I change ids)
https://greendelta.github.io/olca-ipc.py/olca/ipc.html#olca.ipc.Client.upstream_tree_of
I've got this error:
ERROR:root:Failed to get upstream tree: 400: invalid result reference: no ID

Exporting the calculate result with to_json() is ok.

I've tried with all archived beta versions of openLCA (Linux)
With the last (2022-11-07) it's worst: to_json() is empty

Thanks for any help.

**Comment by msrocka** [comment]
Version 2.0.3 now contains an `utree` module that directly uses the IPC calls, this should be easier to use now. An example is available here: https://greendelta.github.io/openLCA-ApiDoc/results/impacts/upstream_trees.html#olca-ipcpy
