### ISSUE TITLE
olca-ipc import error

### ISSUE THREAD

**Issue by pricarious** [GreenDelta/olca-ipc.py#29]
OpenLCA 2.0.0 is installed in my system and the library has been downloaded using pip install olca-ipc.However, when I try to import it in python (jupyter notebook). I get an error of "No module named 'olca_ipc'". Just to check if it is a version compatibility issue I also tried to download olca-ipc 0.0.11 through Terminal and get the message of requirement already satisfied.

**Comment by msrocka** [comment]
The latest olca-ipc module requires Python >= 3.11. Which Python version do you have installed?

**Comment by pricarious** [comment]
I have 3.11 installed
<img width="1267" alt="Screenshot 2023-07-08 at 4 28 52 PM" src="https://github.com/GreenDelta/olca-ipc.py/assets/98677561/bceaccd0-5fc2-4b27-8da6-04ed202c8dfd">

**Comment by pwierzgala** [comment]
This looks like a typical problem with a `PYTHONPATH`. Please check if your notebook runs in the same environment in which you have installed `olca-ipc`. For that you can run `pip list` in the notebook cell. You should have `olca-ipc 2.0.0` on the list.

![image](https://github.com/GreenDelta/olca-ipc.py/assets/5190493/3722e832-e517-4662-88dc-88257be01a38)

**Comment by pricarious** [comment]
I think this was a path issue but the problem is on .zsh the default path for python env and alias path for python environment get messed up while trying to manage .bash_profile and .zshrc. I believe with the Ventura update, some guidance on solving path issues with installing external packages like olca-ipc would be helpful, thanks you for your time, appreciate it
