### ISSUE TITLE
not able to add output avoided exchange

### ISSUE THREAD

**Issue by pwierzgala** [GreenDelta/olca-ipc.py#30]
# Problem definition

I'd like to add an avoided (`is_avoided_product=True`) output (`is_input=False`) exchange to a process but:

- Open LCA displays the exchange on the list of input exchanges (instead of output exchanges).
-  When I get it with `olca_ipc` it has `is_input` attribute set to `False`, which is correct but it doesn't correspond with what I see in Open LCA.
- When I set `is_avoided_product` to `False` the exchange is displayed in Open LCA as expected.

# Sample code

```
import olca_ipc as ipc
import olca_schema as o
from olca_schema import ProcessType, FlowType


flow = o.Flow()
flow.id = 'my flow'
flow.name = 'my flow'
flow.flow_type = FlowType.PRODUCT_FLOW

exchange = o.Exchange()
exchange.id = 'my exchange'
exchange.amount = 1
exchange.flow = flow
exchange.is_avoided_product = True  # incorrect
# exchange.is_avoided_product = False  # correct
exchange.is_input = False

process = o.Process()
process.id = 'my process'
process.name = 'my process'
process.process_type = ProcessType.UNIT_PROCESS
process.exchanges = [exchange]

client = ipc.Client()
client.put(flow)
client.put(process)

process = client.get(model_type=o.Process, uid='my process')
print(process.exchanges[0].is_input)
```

| ![image](https://github.com/GreenDelta/olca-ipc.py/assets/5190493/449f87d6-148e-4a5a-937f-e50282d65ba9) |
|:--:|
| Results in Open LCA |

# Versions
```
OpenLCA 2.0.0
olca-ipc==2.0.0
olca-schema==0.0.11
```

**Comment by msrocka** [comment]
It is confusing but avoided products should be set with `is_input = true`. I tried to explain this in the schema documentation now: http://greendelta.github.io/olca-schema/classes/Exchange.html#isavoidedproduct

I also added a test which demonstrates this behavior: https://github.com/GreenDelta/olca-ipc.py/blob/master/tests/test_avoided_flows.py
