### ISSUE TITLE
Setting "is_avoided_product" for an Exchange reverse it from an output to an input

### ISSUE THREAD

**Issue by Nezertiam** [GreenDelta/olca-ipc.py#37]
## Dependencies
olca-ipc = 2.0.3
olca-schema = 2.2.1
olca = 2.3

## Issue description
Hi,

While creating an Exchange as an output with the property `is_input=False` everything works fine.

But then, I create the same Exchange with `is_avoided_product=True` and it makes it an input with the column `avoided_waste `checked.

Did I do something wrong?

By the way, with this configuration, the creation date for new processes/flows fails to parse.

Thanks for your reply!

**Comment by msrocka** [comment]
Yes, this is how it is supposed to work and it is described in the schema documentation: 

https://greendelta.github.io/olca-schema/classes/Exchange.html#isavoidedproduct

Regarding the error with the creation date, it should be fixed in the latest version (2.2.2) of `olca-schema`.

**Comment by Nezertiam** [comment]
Thanks for your reply! Have a nice day!
