### ISSUE TITLE
AllocationType not set properly using IPC

### ISSUE THREAD

**Issue by gthoma** [GreenDelta/olca-ipc.py#7]
for my product system, i get different results when I run manually in OLCA and there are different results depending on the allocation selection (none vs. as defined in process). However,
regardless of teh AllocationType definition in the code below, the result returned is the same as choosing 'none' in the dropdown menu. 
tst =['product system name']
for sc in tst:

    setup = olca.CalculationSetup()
    setup.calculation_type = olca.CalculationType.CONTRIBUTION_ANALYSIS
    setup.allocation_method = olca.AllocationType.ECONOMIC_ALLOCATION
    setup.impact_method = client.find(olca.ImpactMethod, 'ReCiPe 2016 Midpoint (H)')
    setup.product_system = client.find(olca.ProductSystem, sc)
    setup.amount = 1.0
    result = client.calculate(setup)
    client.excel_export(result, sc + 'ea.xlsx')
    client.dispose(result)

**Comment by btciavol** [comment]
I've been having the same problem, is there any update on this issue? I see in the responses to #11 that there may be a fix slated for openLCA 2.0, but only a win64 version is available. Is it possible to get an OS X build of 2.0, or will the fix be making into the stable release soon?

**Comment by btciavol** [comment]
I've been having the same issue - it appears from one of the responses to #11 that there's a fix slated for v2.0. Is there a chance of the fix making it into a stable build soon? Otherwise would it be possible to get an OS X build of 2.0?

**Comment by bl-young** [comment]
The [test for allocation method](https://github.com/GreenDelta/olca-ipc.py/blob/v2/tests/test_allocation.py) is no longer successful. It has not been updated with the latest changes to the module names, e.g.,:
`import olca as ipc`
`AttributeError: 'Result' object has no attribute 'flow_results'`

I am still having trouble getting the results in v2 to align with the selected allocation method

**Comment by msrocka** [comment]
closing as this is probably not an issue anymore in current versions; for allocation there is also a working test case  https://github.com/GreenDelta/olca-ipc.py/blob/master/tests/test_allocation.py
