### ISSUE TITLE
Release current build on pypi?

### ISSUE THREAD

**Issue by ezrakahn** [GreenDelta/olca-ipc.py#8]
some class attributes in the current build would be super handy.  Like create_product_system.  When will this build be released on pypi?

Thanks!!

**Comment by gthoma** [comment]
yes. PLEASE!!! I have tried installing this release manually, but it does not work. This functionality would be immensely useful for several of my projects.

**Comment by msrocka** [comment]
I uploaded a new `0.0.10` version: https://pypi.org/project/olca-ipc/.

Note that the doc is now hosted on Github: https://greendelta.github.io/olca-ipc.py/olca/

I am closing this issue now. If there are other issues with this package please just open another issue. Thanks!
